-- ALERTA: Ejecuta este código en tu editor SQL de Supabase para arreglar el error

-- 1. Si la tabla ya existe y tiene datos, solo agrega la columna:
alter table registrations add column country text;

-- 2. Si prefieres borrar la tabla y crearla de cero (perderás datos antiguos):
-- drop table registrations;
-- create table registrations (
--   id bigint generated by default as identity primary key,
--   created_at timestamp with time zone default timezone('utc'::text, now()) not null,
--   full_name text not null,
--   email text not null,
--   whatsapp text not null,
--   country text
-- );
